services:
  freshemeatretailer:
    container_name: freshemeatretailercontainer
    build: .
    image: freshemeatretailer:v1
    ports:
      - 8084:4200
    expose:
      - 8084
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
